export const actions = {
  fetchFacilitys: 'FETCH_FACILITYS',
  fetchFacilitysSuccess: 'FETCH_FACILITYS_SUCCCESS',
  fetchFacilitysError: 'FETCH_FACILITYS_ERROR',
  fetchChannels: 'FETCH_CHANNELS',
  fetchChannelsSuccess: 'FETCH_CHANNELS_SUCCESS',
  fetchChannelsError: 'FETCH_CHANNELS_ERROR',
  setterRestaurant: 'SETTER_RESTAURANT',
  addCanales: 'ADD_CANALES',
  deleteCanales: 'DELETE_CANALES',
  fetchRestaurant: 'FETCH_RESTAURANT',
  fetchRestaurantSuccess: 'FETCH_RESTAURANT_SUCCESS',
  fetchRestaurantError: 'FETCH_RESTAURANT_ERROR',
  saveRestaurant: 'SAVE_RESTAURANT',
  saveRestaurantSuccess: 'SAVE_RESTAURANT_SUCCESS',
  saveRestaurantError: 'SAVE_RESTAURANT_ERROR',
};